test

diff --git a/kubernetes/main/apps/media/qbittorrent/app/helmrelease.yaml b/kubernetes/main/apps/media/qbittorrent/app/helmrelease.yaml
--- a/kubernetes/main/apps/media/qbittorrent/app/helmrelease.yaml
+++ b/kubernetes/main/apps/media/qbittorrent/app/helmrelease.yaml
@@ -1,9 +1,11 @@
 ---
-#yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
+# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
 apiVersion: helm.toolkit.fluxcd.io/v2
 kind: HelmRelease
 metadata:
   name: qbittorrent
+  annotations:
+    kustomize.toolkit.fluxcd.io/substitute: disabled
 spec:
   interval: 30m
   chart:
@@ -212,3 +214,267 @@ spec:
           qbittorrent:
             git-sync:
               - path: /tmp
+
+    rawResources:
+      secret:
+        enabled: true
+        apiVersion: external-secrets.io/v1beta1
+        kind: ExternalSecret
+        spec:
+          spec:
+            secretStoreRef:
+              kind: ClusterSecretStore
+              name: vault-backend
+            target:
+              name: *secret
+              template:
+                engineVersion: v2
+                data:
+                  CROSS_SEED_API_KEY: '{{ "{{ .CROSS_SEED_API_KEY }}" }}'
+                  PUSHOVER_TOKEN: '{{ "{{ .QBITTORRENT_PUSHOVER_TOKEN }}" }}'
+                  PUSHOVER_USER_KEY: '{{ "{{ .PUSHOVER_USER_KEY }}" }}'
+            dataFrom:
+              - extract:
+                  key: secrets/api-keys
+              - extract:
+                  key: secrets/pushover
+              - extract:
+                  key: secrets/qbittorrent
+
+      volsync-secret:
+        enabled: true
+        apiVersion: external-secrets.io/v1beta1
+        kind: ExternalSecret
+        spec:
+          spec:
+            secretStoreRef:
+              kind: ClusterSecretStore
+              name: vault-backend
+            target:
+              name: &volsync-secret qbittorrent-volsync-secret
+              template:
+                engineVersion: v2
+                data:
+                  RESTIC_REPOSITORY: '{{ "{{ .RESTIC_REPOSITORY }}/qbittorrent/volsync/config-volsync-config" }}'
+                  RESTIC_PASSWORD: '{{ "{{ .ENCRYPTION_KEY }}" }}'
+                  AWS_ACCESS_KEY_ID: '{{ "{{ .CF_ACCESS_KEY_ID }}" }}'
+                  AWS_SECRET_ACCESS_KEY: '{{ "{{ .CF_SECRET_ACCESS_KEY }}" }}'
+            dataFrom:
+              - extract:
+                  key: secrets/volsync
+              - extract:
+                  key: secrets/cloudflare
+
+      volsync-src:
+        enabled: true
+        apiVersion: volsync.backube/v1alpha1
+        kind: ReplicationSource
+        spec:
+          spec:
+            sourcePVC: qbittorrent-config
+            trigger:
+              schedule: "0 7 * * *"
+            restic:
+              copyMethod: Clone
+              storageClassName: &storageClass openebs-zfs-128k
+              pruneIntervalDays: 7
+              repository: *volsync-secret
+              cacheCapacity: 2Gi
+              moverSecurityContext: &moverSecurityContext
+                runAsUser: 2000
+                runAsGroup: 2000
+                fsGroup: 2000
+              retain:
+                daily: 7
+                within: 3d
+
+      volsync-dst:
+        enabled: false
+        apiVersion: volsync.backube/v1alpha1
+        kind: ReplicationDestination
+        spec:
+          spec:
+            trigger:
+              manual: restore-once
+            restic:
+              repository: *volsync-secret
+              destinationPVC: qbittorrent-config
+              copyMethod: Snapshot
+              storageClassName: *storageClass
+              moverSecurityContext: *moverSecurityContext
+
+    configMaps:
+      gatus-ep:
+        enabled: true
+        labels:
+          gatus.io/enabled: "true"
+        data:
+          config.yaml: |
+            endpoints:
+              - name: "qBittorrent"
+                group: guarded
+                url: "https://qbittorrent.darkfellanetwork.com/api/v2/app/version"
+                interval: 1m
+                ui:
+                  hide-hostname: true
+                  hide-url: true
+                client:
+                  dns-resolver: tcp://172.17.0.10:53
+                conditions:
+                  - "[STATUS] == 403"
+                alerts:
+                  - type: pushover
+
+      loki-rules:
+        enabled: true
+        labels:
+          loki_rule: "true"
+        data:
+          qbittorrent.yaml: |
+            groups:
+              - name: qbittorrent
+                rules:
+                  - alert: QbittorrentFastResumeRejected
+                    expr: |
+                      sum by (app) (count_over_time({app="qbittorrent"} |~ "(?i)fast resume rejected"[1h])) > 0
+                    for: 2m
+                    labels:
+                      severity: critical
+                      category: logs
+                    annotations:
+                      app: "{{ $labels.container }}"
+                      summary: "{{ $labels.container }} has a torrent with fast resume rejected"
+
+      scripts:
+        enabled: true
+        data:
+          healthcheck.sh: |
+            #!/bin/bash
+
+            http_code=$(curl -s -o /dev/null -w "%{http_code}" http://localhost:80/api/v2/app/version)
+            if [[ $http_code != 200 ]]; then
+                log "App status: not up yet, did you enable \"Bypass authentication for clients on localhost\" in the Web UI options?"
+                exit 1
+            else
+                log "App status: up and running"
+            fi
+
+            exit 0
+          post-process.sh: |
+            #!/usr/bin/env bash
+            # shellcheck disable=SC2154
+
+            set -euo pipefail
+
+            # User-defined variables
+            CROSS_SEED_ENABLED="${CROSS_SEED_ENABLED:-false}"
+            CROSS_SEED_HOST="${CROSS_SEED_HOST:-required}"
+            CROSS_SEED_API_KEY="${CROSS_SEED_API_KEY:-required}"
+            CROSS_SEED_SLEEP_INTERVAL="${CROSS_SEED_SLEEP_INTERVAL:-30}"
+            PUSHOVER_ENABLED="${PUSHOVER_ENABLED:-false}"
+            PUSHOVER_USER_KEY="${PUSHOVER_USER_KEY:-required}"
+            PUSHOVER_TOKEN="${PUSHOVER_TOKEN:-required}"
+
+            # Function to set release variables from SABnzbd
+            set_sab_vars() {
+                RELEASE_NAME="${SAB_FILENAME:-}"
+                RELEASE_DIR="${SAB_COMPLETE_DIR:-}"
+                RELEASE_CAT="${SAB_CAT:-}"
+                RELEASE_SIZE="${SAB_BYTES:-}"
+                RELEASE_STATUS="${SAB_PP_STATUS:-}"
+                RELEASE_INDEXER="${SAB_URL:-}"
+                RELEASE_TYPE="NZB"
+            }
+
+            # Function to set release variables from qBittorrent
+            set_qb_vars() {
+                RELEASE_NAME="$1"      # %N
+                RELEASE_DIR="$2"       # %F
+                RELEASE_CAT="$3"       # %L
+                RELEASE_SIZE="$4"      # %Z
+                RELEASE_INDEXER="$5"   # %T
+                RELEASE_STATUS=0       # Always 0 for qBittorrent
+                RELEASE_TYPE="Torrent"
+            }
+
+            # Function to send pushover notification
+            send_pushover_notification() {
+                local pushover_message status_code json_data
+                printf -v pushover_message \
+                    "<b>%s</b><small>\n<b>Category:</b> %s</small><small>\n<b>Indexer:</b> %s</small><small>\n<b>Size:</b> %s</small>" \
+                        "${RELEASE_NAME%.*}" \
+                        "${RELEASE_CAT}" \
+                        "$(trurl --url "${RELEASE_INDEXER}" --get '{idn:host}')" \
+                        "$(numfmt --to iec --format "%8.2f" "${RELEASE_SIZE}")"
+
+                json_data=$(jo \
+                    token="${PUSHOVER_TOKEN}" \
+                    user="${PUSHOVER_USER_KEY}" \
+                    title="${RELEASE_TYPE} Downloaded" \
+                    message="${pushover_message}" \
+                    priority="-2" \
+                    html="1"
+                )
+
+                status_code=$(curl \
+                    --silent \
+                    --write-out "%{http_code}" \
+                    --output /dev/null \
+                    --request POST  \
+                    --header "Content-Type: application/json" \
+                    --data-binary "${json_data}" \
+                    "https://api.pushover.net/1/messages.json"
+                )
+
+                printf "pushover notification returned with HTTP status code %s and payload: %s\n" \
+                    "${status_code}" \
+                    "$(echo "${json_data}" | jq --compact-output)" >&2
+            }
+
+            # Function to search for cross-seed
+            search_cross_seed() {
+                local status_code
+                status_code=$(curl \
+                    --silent \
+                    --output /dev/null \
+                    --write-out "%{http_code}" \
+                    --request POST \
+                    --data-urlencode "path=${RELEASE_DIR}" \
+                    --header "X-Api-Key: ${CROSS_SEED_API_KEY}" \
+                    "https://${CROSS_SEED_HOST}/api/webhook"
+                )
+
+                printf "cross-seed search returned with HTTP status code %s and path %s\n" \
+                    "${status_code}" \
+                    "${RELEASE_DIR}" >&2
+
+                sleep "${CROSS_SEED_SLEEP_INTERVAL}"
+            }
+
+            main() {
+                # Determine the source and set release variables accordingly
+                if env | grep -q "^SAB_"; then
+                    set_sab_vars
+                else
+                    set_qb_vars "$@"
+                fi
+
+                # Check if post-processing was successful
+                if [[ "${RELEASE_STATUS}" -ne 0 ]]; then
+                    printf "post-processing failed with sabnzbd status code %s\n" \
+                        "${RELEASE_STATUS}" >&2
+                    exit 1
+                fi
+
+                # Send pushover notification
+                if [[ "${PUSHOVER_ENABLED}" == "true" ]]; then
+                    send_pushover_notification
+                fi
+
+                # Search for cross-seed
+                if [[ "${CROSS_SEED_ENABLED}" == "true" ]]; then
+                    search_cross_seed
+                fi
+            }
+
+            main "$@"
