test

diff --git a/kubernetes/bootstrap/helmfile.yaml b/kubernetes/bootstrap/helmfile.yaml
--- a/kubernetes/bootstrap/helmfile.yaml
+++ b/kubernetes/bootstrap/helmfile.yaml
@@ -7,33 +7,12 @@ helmDefaults:
   waitForJobs: true
   # waitRetries: 3 # Not supported by Helm yet
 
-repositories:
-  - name: controlplaneio
-    url: ghcr.io/controlplaneio-fluxcd/charts
-    oci: true
-
-  - name: coredns
-    url: ghcr.io/coredns/charts
-    oci: true
-
-  - name: external-secrets
-    url: ghcr.io/external-secrets/charts
-    oci: true
-
-  - name: app-template
-    url: ghcr.io/bjw-s/helm
-    oci: true
-
-  - name: charts-mirror
-    url: ghcr.io/d4rkfella/charts-mirror
-    oci: true
-
 releases:
 
   - name: cilium
     namespace: kube-system
     atomic: true
-    chart: charts-mirror/cilium
+    chart: oci://ghcr.io/d4rkfella/charts-mirror/cilium
     version: 1.17.1
     values: ['{{ requiredEnv "ROOT_DIR" }}/kubernetes/apps/kube-system/cilium/app/helm/values.yaml']
     hooks:
@@ -69,7 +48,7 @@ releases:
   - name: coredns
     namespace: kube-system
     atomic: true
-    chart: coredns/coredns
+    chart: oci://ghcr.io/coredns/charts/coredns
     version: 1.39.1
     values: ['{{ requiredEnv "ROOT_DIR" }}/kubernetes/apps/kube-system/coredns/app/helm/values.yaml']
     needs: ['kube-system/cilium']
@@ -77,7 +56,7 @@ releases:
   - name: kubelet-csr-approver
     namespace: kube-system
     atomic: true
-    chart: charts-mirror/kubelet-csr-approver
+    chart: oci://ghcr.io/d4rkfella/charts-mirror/kubelet-csr-approver
     version: 1.2.6
     values: ['{{ requiredEnv "ROOT_DIR" }}/kubernetes/apps/kube-system/kubelet-csr-approver/app/helm/values.yaml']
     needs: ['kube-system/coredns']
@@ -85,7 +64,7 @@ releases:
   - name: cert-manager
     namespace: cert-manager
     atomic: true
-    chart: charts-mirror/cert-manager
+    chart: oci://ghcr.io/d4rkfella/charts-mirror/cert-manager
     version: v1.17.1
     values: ['{{ requiredEnv "ROOT_DIR" }}/kubernetes/apps/cert-manager/cert-manager/app/helm/values.yaml']
     needs: ['kube-system/kubelet-csr-approver']
@@ -130,7 +109,7 @@ releases:
   - name: external-secrets
     namespace: external-secrets
     atomic: true
-    chart: external-secrets/external-secrets
+    chart: oci://ghcr.io/external-secrets/charts/external-secrets
     version: 0.14.4
     values: ['{{ requiredEnv "ROOT_DIR" }}/kubernetes/apps/external-secrets/external-secrets/app/helm/values.yaml']
     needs: ['vault/vault','cert-manager/cert-manager']
@@ -163,7 +142,7 @@ releases:
   - name: zfs-localpv
     namespace: openebs-system
     atomic: true
-    chart: charts-mirror/zfs-localpv
+    chart: oci://ghcr.io/d4rkfella/charts-mirror/zfs-localpv
     version: 2.7.1
     values: ['{{ requiredEnv "ROOT_DIR" }}/kubernetes/apps/openebs-system/zfs-localpv/app/helm/values.yaml']
     needs: ['kube-system/cilium','kube-system/coredns']
@@ -204,7 +183,7 @@ releases:
   - name: vault
     namespace: vault
     atomic: true
-    chart: charts-mirror/vault
+    chart: oci://ghcr.io/d4rkfella/charts-mirror/vault
     version: 0.29.1
     values: ['{{ requiredEnv "ROOT_DIR" }}/kubernetes/apps/secrets-management/hashicorp-vault/app/helm/values.yaml']
     needs: ['cert-manager/cert-manager','openebs-system/zfs-localpv']
@@ -305,10 +284,9 @@ releases:
   - name: multus
     namespace: kube-system
     atomic: true
-    chart: app-template/app-template
+    chart: oci://ghcr.io/bjw-s/helm/app-template
     version: 3.7.3
     values: ['{{ requiredEnv "ROOT_DIR" }}/kubernetes/apps/kube-system/multus/app/helm/values.yaml']
-    needs: ['kube-system/cilium']
     hooks:
     - events: ["postsync"]
       command: kubectl
@@ -321,13 +299,15 @@ releases:
     - events: ["postsync"]
       command: bash
       args:
-        - c
+        - -c
         - |
-          urls=$(yq '.resources[] | select(test("^https"))' {{ requiredEnv "ROOT_DIR" }}/kubernetes/apps/kubevirt/kubevirt/app/kustomization.yaml {{ requiredEnv "ROOT_DIR" }}/kubernetes/apps/cdi/cdi-operator/app/kustomization.yaml)
+          urls=$(yq '.resources[] | select(test("^https"))' {{ requiredEnv "ROOT_DIR" }}/kubernetes/apps/kubevirt/kubevirt/app/kustomization.yaml {{ requiredEnv "ROOT_DIR" }}/kubernetes/apps/cdi/cdi/app/kustomization.yaml)
 
           for url in $urls; do
-              echo "Applying: $url"
-              kubectl apply --server-side -f "$url"
+              if [[ "$url" =~ ^https:// ]]; then
+                  echo "Applying: $url"
+                  kubectl apply -f "$url"
+              fi
           done
           echo "All CRDs applied successfully!"
       showlogs: true
@@ -388,6 +368,48 @@ releases:
       command: bash
       args:
         - -c
+        - |
+          echo "Checking if all required deployments and daemonsets are running..."
+
+          KUBEVIRT_DEPLOYMENTS=("virt-operator" "virt-controller" "virt-api")
+          KUBEVIRT_DAEMONSETS=("virt-handler")
+
+          CDI_DEPLOYMENTS=("cdi-uploadproxy" "cdi-operator" "cdi-deployment" "cdi-apiserver")
+
+          check_deployment_status() {
+            NAMESPACE=$1
+            DEPLOYMENT=$2
+            echo "Checking deployment $DEPLOYMENT in namespace $NAMESPACE"
+            kubectl -n $NAMESPACE rollout status deployment/$DEPLOYMENT --timeout=2m
+            if [ $? -ne 0 ]; then
+              echo "Deployment $DEPLOYMENT in namespace $NAMESPACE is not running or failed to roll out. Exiting."
+              exit 1
+            fi
+          }
+
+          for DEPLOYMENT in "${KUBEVIRT_DEPLOYMENTS[@]}"; do
+            check_deployment_status "kubevirt" $DEPLOYMENT
+          done
+
+          for DAEMONSET in "${KUBEVIRT_DAEMONSETS[@]}"; do
+            echo "Checking daemonset $DAEMONSET in namespace kubevirt"
+            kubectl -n kubevirt rollout status daemonset/$DAEMONSET --timeout=2m
+            if [ $? -ne 0 ]; then
+              echo "Daemonset $DAEMONSET in namespace kubevirt is not running or failed to roll out. Exiting."
+              exit 1
+            fi
+          done
+
+          for DEPLOYMENT in "${CDI_DEPLOYMENTS[@]}"; do
+            check_deployment_status "cdi" $DEPLOYMENT
+          done
+
+          echo "All required deployments and daemonsets are running."
+      showlogs: true
+    - events: ["postsync"]
+      command: bash
+      args:
+        - -c
         - until kubectl get crd virtualmachines.kubevirt.io datavolumes.cdi.kubevirt.io &>/dev/null; do sleep 10; done
       showlogs: true
     - events: ["postsync"]
@@ -402,5 +424,4 @@ releases:
         - --filename={{ requiredEnv "ROOT_DIR" }}/kubernetes/apps/virtualization/truenas-scale/app/vfiobinding.yaml
         - --filename={{ requiredEnv "ROOT_DIR" }}/kubernetes/apps/virtualization/truenas-scale/app/multus-network.yaml
         - --filename={{ requiredEnv "ROOT_DIR" }}/kubernetes/apps/virtualization/truenas-scale/app/virtualmachine.yaml
-
       showlogs: true
