test

diff --git a/kubernetes/bootstrap/helmfile.yaml b/kubernetes/bootstrap/helmfile.yaml
--- a/kubernetes/bootstrap/helmfile.yaml
+++ b/kubernetes/bootstrap/helmfile.yaml
@@ -86,24 +86,25 @@ releases:
     chart: jetstack/cert-manager
     version: v1.17.1
     values: ['{{ requiredEnv "ROOT_DIR" }}/kubernetes/apps/cert-manager/cert-manager/app/helm/values.yaml']
+    needs: ['kube-system/kubelet-csr-approver']
     hooks:
       - events: ["prepare"]
         command: bash
         args:
           - -c
           - |
-            if ! kubectl get namespace {{ .Release.Namespace }} &>/dev/null; then
-              echo "Namespace {{ .Release.Namespace }} does not exist. Creating it..."
-              kubectl create namespace {{ .Release.Namespace }}
+            if ! kubectl get namespace "{{`{{ .Release.Namespace }}`}}" &>/dev/null; then
+              echo "Namespace "{{`{{ .Release.Namespace }}`}}" does not exist. Creating it..."
+              kubectl create namespace "{{`{{ .Release.Namespace }}`}}"
             else
-              echo "Namespace {{ .Release.Namespace }} already exists."
+              echo "Namespace "{{`{{ .Release.Namespace }}`}}" already exists."
             fi
         showlogs: true
       - events: ['postsync']
         command: bash
         args:
           - -c
-          - until kubectl get crd clusterissuers.cert-manager.io &>/dev/null; do sleep 10; done
+          - until kubectl get crd clusterissuers.cert-manager.io certificates.cert-manager.io &>/dev/null; do sleep 10; done
         showlogs: true
       - events: ['postsync']
         command: bash
@@ -114,11 +115,18 @@ releases:
         command: kubectl
         args:
           - apply
-          - --namespace=kube-system
           - --server-side
           - --field-manager=kustomize-controller
-          - --filename={{ requiredEnv "ROOT_DIR" }}/kubernetes/apps/kube-system/cilium/app/networks.yaml
+          - --filename={{ requiredEnv "ROOT_DIR" }}/kubernetes/apps/cert-manager/cert-manager/app/clusterissuer.yaml
         showlogs: true
+      - events: ['postsync']
+        command: kubectl
+        args:
+          - apply
+          - --namespace=vault
+          - --server-side
+          - --field-manager=kustomize-controller
+          - --filename={{ requiredEnv "ROOT_DIR" }}/kubernetes/apps/secrets-management/hashicorp-vault/app/certificate.yaml
 
   - name: external-secrets
     namespace: external-secrets
@@ -126,28 +134,27 @@ releases:
     chart: external-secrets/external-secrets
     version: 0.14.4
     values: ['{{ requiredEnv "ROOT_DIR" }}/kubernetes/apps/external-secrets/external-secrets/app/helm/values.yaml']
+    needs: ['vault/vault','cert-manager/cert-manager']
     hooks:
       - events: ["prepare"]
         command: bash
         args:
           - -c
           - |
-            if ! kubectl get namespace {{ .Release.Namespace }} &>/dev/null; then
-              echo "Namespace {{ .Release.Namespace }} does not exist. Creating it..."
-              kubectl create namespace {{ .Release.Namespace }}
+            if ! kubectl get namespace "{{`{{ .Release.Namespace }}`}}" &>/dev/null; then
+              echo "Namespace "{{`{{ .Release.Namespace }}`}}" does not exist. Creating it..."
+              kubectl create namespace "{{`{{ .Release.Namespace }}`}}"
             else
-              echo "Namespace {{ .Release.Namespace }} already exists."
+              echo "Namespace "{{`{{ .Release.Namespace }}`}}" already exists."
             fi
         showlogs: true
-      - # Wait for external-secrets CRDs to be available
-        events: ['postsync']
+      - events: ['postsync']
         command: bash
         args:
           - -c
           - until kubectl get crd clustersecretstores.external-secrets.io &>/dev/null; do sleep 10; done
         showlogs: true
-      - # Apply cluster secret store configuration
-        events: ['postsync']
+      - events: ['postsync']
         command: kubectl
         args:
           - apply
@@ -156,7 +163,6 @@ releases:
           - --field-manager=kustomize-controller
           - --filename={{ requiredEnv "ROOT_DIR" }}/kubernetes/apps/external-secrets/external-secrets/app/clustersecretstore.yaml
         showlogs: true
-    needs: ['cert-manager/cert-manager']
 
   - name: zfs-localpv
     namespace: openebs-system
@@ -164,18 +170,42 @@ releases:
     chart: zfs-localpv/zfs-localpv
     version: 2.7.1
     values: ['{{ requiredEnv "ROOT_DIR" }}/kubernetes/apps/openebs-system/zfs-localpv/app/helm/values.yaml']
+    needs: ['kube-system/cilium','kube-system/coredns']
     hooks:
       - events: ["prepare"]
         command: bash
         args:
           - -c
           - |
-            if ! kubectl get namespace {{ .Release.Namespace }} &>/dev/null; then
-              echo "Namespace {{ .Release.Namespace }} does not exist. Creating it..."
-              kubectl create namespace {{ .Release.Namespace }}
+            if ! kubectl get namespace "{{`{{ .Release.Namespace }}`}}" &>/dev/null; then
+              echo "Namespace "{{`{{ .Release.Namespace }}`}}" does not exist. Creating it..."
+              kubectl create namespace "{{`{{ .Release.Namespace }}`}}"
             else
-              echo "Namespace {{ .Release.Namespace }} already exists."
+              echo "Namespace "{{`{{ .Release.Namespace }}`}}" already exists."
             fi
+        showlogs: true
+      - events: ['presync']
+        command: kubectl
+        args:
+          - apply
+          - --namespace=kube-system
+          - --server-side
+          - --field-manager=kustomize-controller
+          - --filename={{ requiredEnv "ROOT_DIR" }}/kubernetes/bootstrap/create-zpool.yaml
+        showlogs: true
+      - events: ['postsync']
+        command: bash
+        args:
+          - -c
+          - until kubectl get crd volumesnapshotclasses.snapshot.storage.k8s.io &>/dev/null; do sleep 10; done
+        showlogs: true
+      - events: ['postsync']
+        command: kubectl
+        args:
+          - apply
+          - --server-side
+          - --field-manager=kustomize-controller
+          - --filename={{ requiredEnv "ROOT_DIR" }}/kubernetes/apps/openebs-system/zfs-localpv/app/storageclass.yaml,{{ requiredEnv "ROOT_DIR" }}/kubernetes/apps/openebs-system/zfs-localpv/app/volumesnapshotclass.yaml
         showlogs: true
 
   - name: vault
@@ -190,33 +220,96 @@ releases:
       args:
         - -c
         - |
-          if ! kubectl get namespace {{ .Release.Namespace }} &>/dev/null; then
-            echo "Namespace {{ .Release.Namespace }} does not exist. Creating it..."
-            kubectl create namespace {{ .Release.Namespace }}
+          if ! kubectl get namespace "{{`{{ .Release.Namespace }}`}}" &>/dev/null; then
+            echo "Namespace "{{`{{ .Release.Namespace }}`}}" does not exist. Creating it..."
+            kubectl create namespace "{{`{{ .Release.Namespace }}`}}"
           else
-            echo "Namespace {{ .Release.Namespace }} already exists."
+            echo "Namespace "{{`{{ .Release.Namespace }}`}}" already exists."
           fi
       showlogs: true
-    - events: ["postsync"]
+    - events: ['prepare']
       command: bash
       args:
         - -c
-        - |
-          vault operator init -format=json -key-shares=1 -key-threshold=1 > /tmp/vault-keys.json
-          vault operator unseal $(cat /tmp/vault-keys.json | jq -r .unseal_keys_b64[0]) || true
+        - sops -d {{ requiredEnv "ROOT_DIR" }}/kubernetes/apps/secrets-management/hashicorp-vault/app/vault.secret.sops.yaml | kubectl apply --server-side --filename - --namespace "{{`{{ .Release.Namespace }}`}}"
       showlogs: true
     - events: ["postsync"]
       command: bash
       args:
         - -c
         - |
+          echo "Waiting for Vault pods to be Running..."
+          while true; do
+            VAULT_PODS=$(kubectl get pods -n vault -l app.kubernetes.io/name=vault -o jsonpath='{.items[*].status.phase}')
+            if echo "$VAULT_PODS" | grep -q "Running" && ! echo "$VAULT_PODS" | grep -q "Pending"; then
+              echo "All Vault pods are Running."
+              break
+            else
+              echo "Vault pods are not yet Running. Waiting..."
+              sleep 10
+            fi
+          done
+
+          export VAULT_ADDR=https://vault.darkfellanetwork.com:8200
+          vault operator init > /tmp/vault-keys.json
+      showlogs: true
+    - events: ["postsync"]
+      command: bash
+      args:
+        - -c
+        - |
+          echo "Waiting for Vault to become unsealed..."
+          export VAULT_ADDR=https://vault.darkfellanetwork.com:8200
+          while true; do
+            VAULT_STATUS=$(vault status 2>/dev/null)
+            if [ $? -eq 0 ]; then
+              SEALED_STATUS=$(echo "$VAULT_STATUS" | grep "Sealed" | awk '{print $2}')
+              if [ "$SEALED_STATUS" == "false" ]; then
+                echo "Vault is unsealed. Proceeding with snapshot restoration..."
+                break
+              else
+                echo "Vault is still sealed. Retrying in 5 seconds..."
+                sleep 5
+              fi
+            else
+              echo "Error: Unable to retrieve Vault status. Retrying in 5 seconds..."
+              sleep 5
+            fi
+          done
+
+          echo "Setting up AWS and Vault environment..."
           export AWS_ENDPOINT_URL=https://2bd80478faceecf0d53c596cd910805f.r2.cloudflarestorage.com
           export AWS_SHARED_CREDENTIALS_FILE={{ requiredEnv "ROOT_DIR" }}/.aws/credentials
+          export VAULT_TOKEN=$(grep 'Initial Root Token:' /tmp/vault-keys.json | awk '{print $4}')
+
+          echo "Fetching the latest snapshot from S3..."
           LATEST_SNAPSHOT=$(aws s3 ls s3://hashicorp-vault-backup/ --endpoint-url=$AWS_ENDPOINT_URL --profile cloudflare-r2 | grep vaultsnapshot- | sort | tail -n 1 | awk '{print $4}')
           aws s3 cp s3://hashicorp-vault-backup/$LATEST_SNAPSHOT . --endpoint-url=$AWS_ENDPOINT_URL --profile cloudflare-r2
-          export VAULT_TOKEN=$(cat /tmp/vault-keys.json | jq -r .root_token)
-          vault operator raft snapshot restore -force $LATEST_SNAPSHOT
+
+          echo "Restoring Vault snapshot (with retry logic)..."
+          MAX_RETRIES=20
+          RETRY_DELAY=2
+          ATTEMPT=1
+          while [ $ATTEMPT -le $MAX_RETRIES ]; do
+            echo "Attempt $ATTEMPT of $MAX_RETRIES..."
+            vault operator raft snapshot restore -force $LATEST_SNAPSHOT
+            if [ $? -eq 0 ]; then
+              echo "Snapshot restored successfully."
+              break
+            else
+              echo "Snapshot restoration failed. Retrying in $RETRY_DELAY seconds..."
+              sleep $RETRY_DELAY
+              ATTEMPT=$((ATTEMPT + 1))
+            fi
+          done
+
+          if [ $ATTEMPT -gt $MAX_RETRIES ]; then
+            echo "Error: Failed to restore snapshot after $MAX_RETRIES attempts."
+            exit 1
+          fi
+          echo "Snapshot restoration complete."
       showlogs: true
+
 
   - name: multus
     namespace: kube-system
@@ -224,6 +317,7 @@ releases:
     chart: app-template/app-template
     version: 3.7.2
     values: ['{{ requiredEnv "ROOT_DIR" }}/kubernetes/apps/kube-system/multus/app/helm/values.yaml']
+    needs: ['kube-system/cilium']
     hooks:
     - events: ["postsync"]
       command: kubectl
